### ISSUE TITLE
Error 'chroot: failed to run command '/.dapp/deps/base/0.1.14/bin/bash': No such file or directory'

### ISSUE THREAD

**Issue by imissyouso** [flant/werf#18]
Hi all. Thank you for your contribution.

When I tried to run basic build command like 'dapp build' with 
the next sample Dappfile content 
```
dimg 'web' do
    docker.from 'php:7.0-fpm'
    git 'git@github.com:flant/dapp.git' do
        add '/' do
            to '/resources/frontend'
        end
  end
end
```
I get error 
```
Andrews-MacBook-Pro-2:web andrew$ dapp build
web
System shellout container failure, try to remove if error persists: docker rm -f dapp_system_shellout_cf6fa6bbac8add9e9296005b33e2445ba1f6fd2e2a6613d59d51eeddf860f9e1
Stacktrace dumped to /tmp/dapp-stacktrace-a8f08481-9bab-4d27-9261-5d957b2a22ea.out
>>> START STREAM
chroot: failed to run command '/.dapp/deps/base/0.1.14/bin/bash': No such file or directory
>>> END STREAM
```
My OS is OSX El Captain

Any ideas? thank you.

**Comment by distol** [comment]
Hi!

First of all, dapp requires docker to run. And for now, docker do not support Mac. Docker [only allows you to use it inside VM](https://docs.docker.com/engine/installation/mac/). You could create VM manually or use some magic tools, like docker-machine, Vagrant or Docker for Mac.

So, unfortunately, for now, the only way to use dapp on Mac is to create VM with Linux.

But, I think we could implement [Docker for Mac](https://docs.docker.com/engine/installation/mac/#/docker-for-mac) support in some near future. How do you use docker on Mac?

**Comment by imissyouso** [comment]
I use 'Docker for Mac'
[https://docs.docker.com/docker-for-mac](url)

> Docker.app is Docker for Mac, a bundle of Docker client, and Docker Engine. Docker.app uses the macOS Hypervisor.framework (part of macOS 10.10 Yosemite and higher) to run containers, meaning that no separate VirtualBox is required.

So I have no problems with running containers via basic docker cli.

**Comment by distol** [comment]
We did some digging and found problems in the dapp internals. Actually, dapp creates service container, to use fixed and predictable versions of some required Linux tools (tar, git, etc). So, for now, the problem is, that we mount into that container the whole system (/ → /mnt/chroot), and "overriding" in that system (using mount's and PATH magic, tools, that are required for dapp).

We decided to reimplement that part:
- use ubuntu:16.04 image, instead of mounting whole base system,
- mount only project dir inside that container,
- implement auto shutdown (and auto removal) of that temporary service container.

We need few days to fix that. If everything goes well it could be done in 24h from now.

And theoretically, after that change dapp will work well with Docker for Mac.

**Comment by distorhead** [comment]
Hi!

Some things more portable now:
* Service container "to use fixed and predictable versions of some required Linux tools", which called system-shellout:
  * is now based on ubuntu:16.04;
  * mounts only project dir and service tmp dirs instead of the whole system;
  * is not running in privileged mode.
* There was an issue with mounting service tmp dirs as docker volumes.
  * By default in mac os tmp dirs are created in `/var/folders`.
  * With default file sharing permissions on mac os `/var/folders/*` is forbidden to be used as docker volumes.
  * So creation of tmp dirs is now forced into `/tmp` (which is more portable anyway) by default.

Status of the issue:
* Version 0.7.15 have passed "test-project building" test.
  * This test project is included into dapp source, here it is: https://github.com/flant/dapp/tree/master/spec/chef/testproject.
* Some dapp internal rspec tests not working on mac os now.
  * 11 of 204 tests failed.
  * All of these failures are related to the way the tests run dapp internals. It means these tests are in fact "disabled" for now and cannot tell us anything useful.
  * The only mac os test machine we have, have gone now for two weeks. So we need to freeze this rspec issue.
* Versions above 0.7.15 not tested for "test-project building" on mac os, but should work ok.
* In version 0.7.17 [rugged](https://github.com/libgit2/rugged) dependency was added. Before 0.7.17 installation run: `brew install cmake` (https://github.com/libgit2/rugged#install).

Since verson 0.7.15 dapp should work on mac os. No 100% guarantee, but we will continue to solve mac os related issues.
